In [37]:
import tensorflow as tf
import numpy as np

------

## tf.zeros(shape, dtype=tf.float32, name=None)

Создаём тензор заданной формы со всеми элементами равными нулю

Например: 

In [78]:
a = tf.zeros([3, 4], tf.int16, 'Zeros')

In [79]:
with tf.Session() as sess:
    print(sess.run(a))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


  ### Параметры:
  shape - форма тензора;
  
  dtype - один из типов;
  
  name - имя операции в графе
  
  * `tf.float16`: 16-bit half-precision floating-point.
  * `tf.float32`: 32-bit single-precision floating-point.
  * `tf.float64`: 64-bit double-precision floating-point.
  * `tf.complex64`: 64-bit single-precision complex.
  * `tf.complex128`: 128-bit double-precision complex.
  * `tf.int8`: 8-bit signed integer.
  * `tf.uint8`: 8-bit unsigned integer.
  * `tf.uint16`: 16-bit unsigned integer.
  * `tf.int16`: 16-bit signed integer.
  * `tf.int32`: 32-bit signed integer.
  * `tf.int64`: 64-bit signed integer.


In [80]:
print([t.name for t in tf.get_default_graph().get_operations()])

['Zeros']


------

## tf.zeros_like(tensor, dtype=None, name=None, optimize=True)

Создаём тензор аналогичный исходному, но со всеми элементами равными нулю

Например: 

In [44]:
a1= np.array([[1,2],[3,4]])

In [45]:
a2 = tf.constant(a1)

In [46]:
a = tf.zeros_like(a2)

In [47]:
with tf.Session() as sess:
    print(sess.run(a))

[[0 0]
 [0 0]]


### Параметры:
tensor - исходный тензор(шаблон)

dtype - Тип для возвращаемого тензора. Должен быть одним из: 
* float32, 
* float64, 
* int8, 
* int16, 
* int32, 
* int64, 
* uint8, 
* complex64, 
* complex128
name - имя операции в графе(опционально)

optimize - принимает значение true и false. В случае, если true - форма тензора будет статически заменена на константу. 

------

## tf.ones(shape, dtype=tf.float32, name=None)

Создаём тензор заданной формы со всеми элементами равными единице

Например: 

In [50]:
a = tf.ones([3, 4], tf.int32, 'Ones')

In [51]:
with tf.Session() as sess:
    print(sess.run(a))

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


  ### Параметры:
  shape - форма тензора;
  
  dtype - один из типов tf из списка ниже;
  
  name - имя операции в графе
  
  * `tf.float16`: 16-bit half-precision floating-point.
  * `tf.float32`: 32-bit single-precision floating-point.
  * `tf.float64`: 64-bit double-precision floating-point.
  * `tf.complex64`: 64-bit single-precision complex.
  * `tf.complex128`: 128-bit double-precision complex.
  * `tf.int8`: 8-bit signed integer.
  * `tf.uint8`: 8-bit unsigned integer.
  * `tf.uint16`: 16-bit unsigned integer.
  * `tf.int16`: 16-bit signed integer.
  * `tf.int32`: 32-bit signed integer.
  * `tf.int64`: 64-bit signed integer.


------

## tf.ones_like(tensor, dtype=None, name=None, optimize=True)

Создаём тензор аналогичный исходному, но со всеми элементами равными единице

Например: 

In [81]:
a1= np.array([[1,2],[3,4]])
a2 = tf.constant(a1)
a = tf.ones_like(a2)

In [82]:
with tf.Session() as sess:
    print(sess.run(a))

[[1 1]
 [1 1]]


### Параметры:
tensor - исходный тензор(шаблон)

dtype - Тип для возвращаемого тензора. Должен быть одним из: 
* float32, 
* float64, 
* int8, 
* int16, 
* int32, 
* int64, 
* uint8, 
* complex64, 
* complex128
name - имя операции в графе(опционально)

optimize - принимает значение true и false. В случае, если true - форма тензора будет статически заменена на константу. 

#### Если тип явно не задан - наследуется из исходного тензора:

In [90]:
a

<tf.Tensor 'ones_like:0' shape=(2, 2) dtype=int64>

In [91]:
a1.dtype

dtype('int64')

------

## tf.fill(dims, value, name=None)

Создаём тензор заполненный скалярным значением 

Например:

In [93]:
a = tf.fill([2, 3], 9)

In [94]:
with tf.Session() as sess:
    print(sess.run(a))

[[9 9 9]
 [9 9 9]]


dims -  Тензор типа int32. 1-D. Либо форма тензора - его shape.

value -  Тензор. 0-D (скаляр). Значение, которым необходимо заполнить.

@compatibility(numpy) эквивалентно np.full @end_compatibility

name - имя операции в графе

In [106]:
a2=tf.constant([2,2],dtype=tf.int32)

In [107]:
a=tf.fill(a2,9)

In [108]:
with tf.Session() as sess:
    print(sess.run(a))

[[9 9]
 [9 9]]


-----

## tf.constant(value, dtype=None, shape=None, name='Const', verify_shape=False)

Создаём тензор констант.

Результирующий тензор может быть указанной формы(N-мерным) и заполнен указанным значением. 

Аргумент value может быть константой или списком значений типа dtype. Если value - это список, тогда длина списка должна быть меньше или равно количеству элементов указанных в параметре shape. Если количество элементов списка меньше количества элементов указанных в shape - тогда последний элемент списка будет размножен. 

Аргумент shape - опционален. Он определеяет форму тензора (количество элементов и измерений). Если он явно не задан, то наследуется из value. 

Если аргумент dtype не определён явно, тогда тип наследуется из value

Например:

In [117]:
a = tf.constant([1, 2, 3, 4, 5, 6, 7])
b = tf.constant(-1.0, shape=[2, 3])
c = tf.constant([0,1,2],shape=[3,4])

In [118]:
with tf.Session() as sess:
    print(sess.run(a))
    print('-------------')
    print(sess.run(b))
    print('-------------')
    print(sess.run(c))

[1 2 3 4 5 6 7]
-------------
[[-1. -1. -1.]
 [-1. -1. -1.]]
-------------
[[0 1 2 2]
 [2 2 2 2]
 [2 2 2 2]]


value - константа, или список типа dtype

dtype - опциональный параметр для определения явного типа результирующего тензора

shape - опциональный параметр определяющий форму тензора

name - опциональный параметр - имя операции

verify_shape - boolean для проверки соответствия формы тензора (0.12)